// <auto-generated />
using System;
using KIM_Style.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KIM_Style.Migrations
{
    [DbContext(typeof(KIM_StyleContext))]
    [Migration("20231103162923_agregaCalificacionPromedio_TablaProducto")]
    partial class agregaCalificacionPromedio_TablaProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KIM_Style.Models.Auditoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("sql")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tabla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("valor_anterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("valor_nuevo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("KIM_Style.Models.Calificacion", b =>
                {
                    b.Property<int>("id_calificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_calificacion"));

                    b.Property<byte>("calificacion")
                        .HasColumnType("tinyint");

                    b.Property<int>("ced_usuario")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("cod_producto")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.HasKey("id_calificacion");

                    b.HasIndex("ced_usuario");

                    b.HasIndex("cod_producto");

                    b.ToTable("Calificacion");
                });

            modelBuilder.Entity("KIM_Style.Models.Color", b =>
                {
                    b.Property<int>("id_color")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_color"));

                    b.Property<string>("color_nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_color");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("KIM_Style.Models.Detalle_Factura", b =>
                {
                    b.Property<int>("id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_detalle"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("cod_producto")
                        .HasColumnType("int");

                    b.Property<int>("id_factura")
                        .HasColumnType("int");

                    b.Property<decimal>("total_producto")
                        .HasColumnType("decimal(11, 2)");

                    b.HasKey("id_detalle");

                    b.HasIndex("cod_producto");

                    b.HasIndex("id_factura");

                    b.ToTable("Detalle_Factua");
                });

            modelBuilder.Entity("KIM_Style.Models.Factura", b =>
                {
                    b.Property<int>("id_factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_factura"));

                    b.Property<string>("estado_venta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("tipo_transaccion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("valor_total")
                        .HasColumnType("decimal(11, 2)");

                    b.HasKey("id_factura");

                    b.HasIndex("id_usuario");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("KIM_Style.Models.Producto", b =>
                {
                    b.Property<int>("cod_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cod_producto"));

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("calificacion_promedio")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_color")
                        .HasColumnType("int");

                    b.Property<byte>("id_tipo_prenda")
                        .HasColumnType("tinyint");

                    b.Property<byte>("marca")
                        .HasColumnType("tinyint");

                    b.Property<string>("material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("talla")
                        .HasColumnType("tinyint");

                    b.Property<string>("temporada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("valor")
                        .HasColumnType("decimal(11, 2)");

                    b.HasKey("cod_producto");

                    b.HasIndex("id_color");

                    b.HasIndex("id_tipo_prenda");

                    b.HasIndex("marca");

                    b.HasIndex("talla");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("KIM_Style.Models.Rol", b =>
                {
                    b.Property<byte>("id_rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("id_rol"));

                    b.Property<string>("nombre_rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_rol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("KIM_Style.Models.Tipo_Marca", b =>
                {
                    b.Property<byte>("id_marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("id_marca"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_marca");

                    b.ToTable("Tipo_Marca");
                });

            modelBuilder.Entity("KIM_Style.Models.Tipo_Prenda", b =>
                {
                    b.Property<byte>("id_prenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("id_prenda"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_prenda");

                    b.ToTable("Tipo_Prenda");
                });

            modelBuilder.Entity("KIM_Style.Models.Tipo_Talla", b =>
                {
                    b.Property<byte>("id_talla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("id_talla"));

                    b.Property<string>("talla")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("id_talla");

                    b.ToTable("Tipo_Talla");
                });

            modelBuilder.Entity("KIM_Style.Models.Usuario", b =>
                {
                    b.Property<int>("cedula")
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoPerfil")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("constrasena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("rol_usuario")
                        .HasColumnType("tinyint");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("cedula");

                    b.HasIndex("rol_usuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("KIM_Style.Models.Calificacion", b =>
                {
                    b.HasOne("KIM_Style.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("ced_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KIM_Style.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("cod_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KIM_Style.Models.Detalle_Factura", b =>
                {
                    b.HasOne("KIM_Style.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("cod_producto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KIM_Style.Models.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("id_factura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("KIM_Style.Models.Factura", b =>
                {
                    b.HasOne("KIM_Style.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("KIM_Style.Models.Producto", b =>
                {
                    b.HasOne("KIM_Style.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("id_color")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KIM_Style.Models.Tipo_Prenda", "Tipo_Prenda")
                        .WithMany()
                        .HasForeignKey("id_tipo_prenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KIM_Style.Models.Tipo_Marca", "Tipo_Marca")
                        .WithMany()
                        .HasForeignKey("marca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KIM_Style.Models.Tipo_Talla", "Tipo_Talla")
                        .WithMany()
                        .HasForeignKey("talla")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Tipo_Marca");

                    b.Navigation("Tipo_Prenda");

                    b.Navigation("Tipo_Talla");
                });

            modelBuilder.Entity("KIM_Style.Models.Usuario", b =>
                {
                    b.HasOne("KIM_Style.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("rol_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
